# Default values for istio-kiali.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

release: ""

replicaCount: 1

CLUSTER_NAME: ""

AmazonEKSClusterAutoscalerRole: ""

ACCOUNT_ID: ""
